language: go

env: 
  - GO111MODULE=on

go:
  - 1.12.x

branches: # build only on these branches
  only:
    - master

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

# Make sure golangci-lint is vendored.
before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run       # run a bunch of code checkers/linters in parallel
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
